version: '3.4'
services:
  web:
    build:
      context: ./src
      dockerfile: Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ConnectionStrings__TestConnection=Server=sqlserver;Database=TestDb;User Id=sa;Password=Password123!;TrustServerCertificate=true;
    ports:
      - "8082:8082"
      - "8083:8083"
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-test
    environment:
      - SA_PASSWORD=Password123!
      - ACCEPT_EULA=Y
    ports:
      - "1435:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password123!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5